// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerRequest.proto

package com.xiwan.NettyGamer.proto;

public final class ServerRequest {
  private ServerRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface msgInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.msgInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 Type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 Type = 1;</code>
     */
    int getType();

    /**
     * <code>repeated string VarTable = 2;</code>
     */
    com.google.protobuf.ProtocolStringList
        getVarTableList();
    /**
     * <code>repeated string VarTable = 2;</code>
     */
    int getVarTableCount();
    /**
     * <code>repeated string VarTable = 2;</code>
     */
    java.lang.String getVarTable(int index);
    /**
     * <code>repeated string VarTable = 2;</code>
     */
    com.google.protobuf.ByteString
        getVarTableBytes(int index);

    /**
     * <code>repeated bytes ObjectTable = 3;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getObjectTableList();
    /**
     * <code>repeated bytes ObjectTable = 3;</code>
     */
    int getObjectTableCount();
    /**
     * <code>repeated bytes ObjectTable = 3;</code>
     */
    com.google.protobuf.ByteString getObjectTable(int index);
  }
  /**
   * Protobuf type {@code protobuf.msgInfo}
   */
  public static final class msgInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.msgInfo)
      msgInfoOrBuilder {
    // Use msgInfo.newBuilder() to construct.
    private msgInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private msgInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final msgInfo defaultInstance;
    public static msgInfo getDefaultInstance() {
      return defaultInstance;
    }

    public msgInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private msgInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                varTable_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              varTable_.add(bs);
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                objectTable_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000004;
              }
              objectTable_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          varTable_ = varTable_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          objectTable_ = java.util.Collections.unmodifiableList(objectTable_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiwan.NettyGamer.proto.ServerRequest.internal_static_protobuf_msgInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiwan.NettyGamer.proto.ServerRequest.internal_static_protobuf_msgInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiwan.NettyGamer.proto.ServerRequest.msgInfo.class, com.xiwan.NettyGamer.proto.ServerRequest.msgInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<msgInfo> PARSER =
        new com.google.protobuf.AbstractParser<msgInfo>() {
      public msgInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new msgInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<msgInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 Type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 Type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int VARTABLE_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList varTable_;
    /**
     * <code>repeated string VarTable = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getVarTableList() {
      return varTable_;
    }
    /**
     * <code>repeated string VarTable = 2;</code>
     */
    public int getVarTableCount() {
      return varTable_.size();
    }
    /**
     * <code>repeated string VarTable = 2;</code>
     */
    public java.lang.String getVarTable(int index) {
      return varTable_.get(index);
    }
    /**
     * <code>repeated string VarTable = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVarTableBytes(int index) {
      return varTable_.getByteString(index);
    }

    public static final int OBJECTTABLE_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> objectTable_;
    /**
     * <code>repeated bytes ObjectTable = 3;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getObjectTableList() {
      return objectTable_;
    }
    /**
     * <code>repeated bytes ObjectTable = 3;</code>
     */
    public int getObjectTableCount() {
      return objectTable_.size();
    }
    /**
     * <code>repeated bytes ObjectTable = 3;</code>
     */
    public com.google.protobuf.ByteString getObjectTable(int index) {
      return objectTable_.get(index);
    }

    private void initFields() {
      type_ = 0;
      varTable_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      objectTable_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      for (int i = 0; i < varTable_.size(); i++) {
        output.writeBytes(2, varTable_.getByteString(i));
      }
      for (int i = 0; i < objectTable_.size(); i++) {
        output.writeBytes(3, objectTable_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < varTable_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(varTable_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getVarTableList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < objectTable_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(objectTable_.get(i));
        }
        size += dataSize;
        size += 1 * getObjectTableList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.xiwan.NettyGamer.proto.ServerRequest.msgInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiwan.NettyGamer.proto.ServerRequest.msgInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiwan.NettyGamer.proto.ServerRequest.msgInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiwan.NettyGamer.proto.ServerRequest.msgInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiwan.NettyGamer.proto.ServerRequest.msgInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xiwan.NettyGamer.proto.ServerRequest.msgInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.xiwan.NettyGamer.proto.ServerRequest.msgInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.xiwan.NettyGamer.proto.ServerRequest.msgInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.xiwan.NettyGamer.proto.ServerRequest.msgInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xiwan.NettyGamer.proto.ServerRequest.msgInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xiwan.NettyGamer.proto.ServerRequest.msgInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.msgInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.msgInfo)
        com.xiwan.NettyGamer.proto.ServerRequest.msgInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiwan.NettyGamer.proto.ServerRequest.internal_static_protobuf_msgInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiwan.NettyGamer.proto.ServerRequest.internal_static_protobuf_msgInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiwan.NettyGamer.proto.ServerRequest.msgInfo.class, com.xiwan.NettyGamer.proto.ServerRequest.msgInfo.Builder.class);
      }

      // Construct using com.xiwan.NettyGamer.proto.ServerRequest.msgInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        varTable_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        objectTable_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiwan.NettyGamer.proto.ServerRequest.internal_static_protobuf_msgInfo_descriptor;
      }

      public com.xiwan.NettyGamer.proto.ServerRequest.msgInfo getDefaultInstanceForType() {
        return com.xiwan.NettyGamer.proto.ServerRequest.msgInfo.getDefaultInstance();
      }

      public com.xiwan.NettyGamer.proto.ServerRequest.msgInfo build() {
        com.xiwan.NettyGamer.proto.ServerRequest.msgInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xiwan.NettyGamer.proto.ServerRequest.msgInfo buildPartial() {
        com.xiwan.NettyGamer.proto.ServerRequest.msgInfo result = new com.xiwan.NettyGamer.proto.ServerRequest.msgInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          varTable_ = varTable_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.varTable_ = varTable_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          objectTable_ = java.util.Collections.unmodifiableList(objectTable_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.objectTable_ = objectTable_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiwan.NettyGamer.proto.ServerRequest.msgInfo) {
          return mergeFrom((com.xiwan.NettyGamer.proto.ServerRequest.msgInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiwan.NettyGamer.proto.ServerRequest.msgInfo other) {
        if (other == com.xiwan.NettyGamer.proto.ServerRequest.msgInfo.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.varTable_.isEmpty()) {
          if (varTable_.isEmpty()) {
            varTable_ = other.varTable_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureVarTableIsMutable();
            varTable_.addAll(other.varTable_);
          }
          onChanged();
        }
        if (!other.objectTable_.isEmpty()) {
          if (objectTable_.isEmpty()) {
            objectTable_ = other.objectTable_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureObjectTableIsMutable();
            objectTable_.addAll(other.objectTable_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xiwan.NettyGamer.proto.ServerRequest.msgInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xiwan.NettyGamer.proto.ServerRequest.msgInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>required int32 Type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 Type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 Type = 1;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList varTable_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureVarTableIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          varTable_ = new com.google.protobuf.LazyStringArrayList(varTable_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string VarTable = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getVarTableList() {
        return varTable_.getUnmodifiableView();
      }
      /**
       * <code>repeated string VarTable = 2;</code>
       */
      public int getVarTableCount() {
        return varTable_.size();
      }
      /**
       * <code>repeated string VarTable = 2;</code>
       */
      public java.lang.String getVarTable(int index) {
        return varTable_.get(index);
      }
      /**
       * <code>repeated string VarTable = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVarTableBytes(int index) {
        return varTable_.getByteString(index);
      }
      /**
       * <code>repeated string VarTable = 2;</code>
       */
      public Builder setVarTable(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVarTableIsMutable();
        varTable_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string VarTable = 2;</code>
       */
      public Builder addVarTable(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVarTableIsMutable();
        varTable_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string VarTable = 2;</code>
       */
      public Builder addAllVarTable(
          java.lang.Iterable<java.lang.String> values) {
        ensureVarTableIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, varTable_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string VarTable = 2;</code>
       */
      public Builder clearVarTable() {
        varTable_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string VarTable = 2;</code>
       */
      public Builder addVarTableBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVarTableIsMutable();
        varTable_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> objectTable_ = java.util.Collections.emptyList();
      private void ensureObjectTableIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          objectTable_ = new java.util.ArrayList<com.google.protobuf.ByteString>(objectTable_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated bytes ObjectTable = 3;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getObjectTableList() {
        return java.util.Collections.unmodifiableList(objectTable_);
      }
      /**
       * <code>repeated bytes ObjectTable = 3;</code>
       */
      public int getObjectTableCount() {
        return objectTable_.size();
      }
      /**
       * <code>repeated bytes ObjectTable = 3;</code>
       */
      public com.google.protobuf.ByteString getObjectTable(int index) {
        return objectTable_.get(index);
      }
      /**
       * <code>repeated bytes ObjectTable = 3;</code>
       */
      public Builder setObjectTable(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureObjectTableIsMutable();
        objectTable_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ObjectTable = 3;</code>
       */
      public Builder addObjectTable(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureObjectTableIsMutable();
        objectTable_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ObjectTable = 3;</code>
       */
      public Builder addAllObjectTable(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureObjectTableIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, objectTable_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ObjectTable = 3;</code>
       */
      public Builder clearObjectTable() {
        objectTable_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.msgInfo)
    }

    static {
      defaultInstance = new msgInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.msgInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_msgInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_msgInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ServerRequest.proto\022\010protobuf\">\n\007msgIn" +
      "fo\022\014\n\004Type\030\001 \002(\005\022\020\n\010VarTable\030\002 \003(\t\022\023\n\013Ob" +
      "jectTable\030\003 \003(\014B+\n\032com.xiwan.NettyGamer." +
      "protoB\rServerRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_msgInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_msgInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_msgInfo_descriptor,
        new java.lang.String[] { "Type", "VarTable", "ObjectTable", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
