// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerResponse.proto

package com.xiwan.NettyGamer.proto;

public final class ServerResponse {
  private ServerResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface payloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.payload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 Type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 Type = 1;</code>
     */
    int getType();

    /**
     * <code>required int32 Ticket = 2;</code>
     */
    boolean hasTicket();
    /**
     * <code>required int32 Ticket = 2;</code>
     */
    int getTicket();

    /**
     * <code>repeated bool BoolList = 3;</code>
     */
    java.util.List<java.lang.Boolean> getBoolListList();
    /**
     * <code>repeated bool BoolList = 3;</code>
     */
    int getBoolListCount();
    /**
     * <code>repeated bool BoolList = 3;</code>
     */
    boolean getBoolList(int index);

    /**
     * <code>repeated int32 IntList = 4;</code>
     */
    java.util.List<java.lang.Integer> getIntListList();
    /**
     * <code>repeated int32 IntList = 4;</code>
     */
    int getIntListCount();
    /**
     * <code>repeated int32 IntList = 4;</code>
     */
    int getIntList(int index);

    /**
     * <code>repeated double DoubleList = 5;</code>
     */
    java.util.List<java.lang.Double> getDoubleListList();
    /**
     * <code>repeated double DoubleList = 5;</code>
     */
    int getDoubleListCount();
    /**
     * <code>repeated double DoubleList = 5;</code>
     */
    double getDoubleList(int index);

    /**
     * <code>repeated string StringList = 6;</code>
     */
    com.google.protobuf.ProtocolStringList
        getStringListList();
    /**
     * <code>repeated string StringList = 6;</code>
     */
    int getStringListCount();
    /**
     * <code>repeated string StringList = 6;</code>
     */
    java.lang.String getStringList(int index);
    /**
     * <code>repeated string StringList = 6;</code>
     */
    com.google.protobuf.ByteString
        getStringListBytes(int index);

    /**
     * <code>repeated int64 DateTimeList = 7;</code>
     */
    java.util.List<java.lang.Long> getDateTimeListList();
    /**
     * <code>repeated int64 DateTimeList = 7;</code>
     */
    int getDateTimeListCount();
    /**
     * <code>repeated int64 DateTimeList = 7;</code>
     */
    long getDateTimeList(int index);

    /**
     * <code>repeated bytes ByteList = 8;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getByteListList();
    /**
     * <code>repeated bytes ByteList = 8;</code>
     */
    int getByteListCount();
    /**
     * <code>repeated bytes ByteList = 8;</code>
     */
    com.google.protobuf.ByteString getByteList(int index);

    /**
     * <code>repeated int64 SeverUnixTime = 9;</code>
     */
    java.util.List<java.lang.Long> getSeverUnixTimeList();
    /**
     * <code>repeated int64 SeverUnixTime = 9;</code>
     */
    int getSeverUnixTimeCount();
    /**
     * <code>repeated int64 SeverUnixTime = 9;</code>
     */
    long getSeverUnixTime(int index);
  }
  /**
   * Protobuf type {@code protobuf.payload}
   */
  public static final class payload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.payload)
      payloadOrBuilder {
    // Use payload.newBuilder() to construct.
    private payload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private payload(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final payload defaultInstance;
    public static payload getDefaultInstance() {
      return defaultInstance;
    }

    public payload getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private payload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ticket_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                boolList_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000004;
              }
              boolList_.add(input.readBool());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                boolList_ = new java.util.ArrayList<java.lang.Boolean>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                boolList_.add(input.readBool());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                intList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              intList_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                intList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                intList_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 41: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                doubleList_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000010;
              }
              doubleList_.add(input.readDouble());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                doubleList_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                doubleList_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                stringList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              stringList_.add(bs);
              break;
            }
            case 56: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                dateTimeList_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000040;
              }
              dateTimeList_.add(input.readInt64());
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040) && input.getBytesUntilLimit() > 0) {
                dateTimeList_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000040;
              }
              while (input.getBytesUntilLimit() > 0) {
                dateTimeList_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                byteList_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000080;
              }
              byteList_.add(input.readBytes());
              break;
            }
            case 72: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                severUnixTime_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000100;
              }
              severUnixTime_.add(input.readInt64());
              break;
            }
            case 74: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100) && input.getBytesUntilLimit() > 0) {
                severUnixTime_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000100;
              }
              while (input.getBytesUntilLimit() > 0) {
                severUnixTime_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          boolList_ = java.util.Collections.unmodifiableList(boolList_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          intList_ = java.util.Collections.unmodifiableList(intList_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          doubleList_ = java.util.Collections.unmodifiableList(doubleList_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          stringList_ = stringList_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          dateTimeList_ = java.util.Collections.unmodifiableList(dateTimeList_);
        }
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          byteList_ = java.util.Collections.unmodifiableList(byteList_);
        }
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          severUnixTime_ = java.util.Collections.unmodifiableList(severUnixTime_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xiwan.NettyGamer.proto.ServerResponse.internal_static_protobuf_payload_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xiwan.NettyGamer.proto.ServerResponse.internal_static_protobuf_payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xiwan.NettyGamer.proto.ServerResponse.payload.class, com.xiwan.NettyGamer.proto.ServerResponse.payload.Builder.class);
    }

    public static com.google.protobuf.Parser<payload> PARSER =
        new com.google.protobuf.AbstractParser<payload>() {
      public payload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new payload(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<payload> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 Type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 Type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int TICKET_FIELD_NUMBER = 2;
    private int ticket_;
    /**
     * <code>required int32 Ticket = 2;</code>
     */
    public boolean hasTicket() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 Ticket = 2;</code>
     */
    public int getTicket() {
      return ticket_;
    }

    public static final int BOOLLIST_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Boolean> boolList_;
    /**
     * <code>repeated bool BoolList = 3;</code>
     */
    public java.util.List<java.lang.Boolean>
        getBoolListList() {
      return boolList_;
    }
    /**
     * <code>repeated bool BoolList = 3;</code>
     */
    public int getBoolListCount() {
      return boolList_.size();
    }
    /**
     * <code>repeated bool BoolList = 3;</code>
     */
    public boolean getBoolList(int index) {
      return boolList_.get(index);
    }

    public static final int INTLIST_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> intList_;
    /**
     * <code>repeated int32 IntList = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getIntListList() {
      return intList_;
    }
    /**
     * <code>repeated int32 IntList = 4;</code>
     */
    public int getIntListCount() {
      return intList_.size();
    }
    /**
     * <code>repeated int32 IntList = 4;</code>
     */
    public int getIntList(int index) {
      return intList_.get(index);
    }

    public static final int DOUBLELIST_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Double> doubleList_;
    /**
     * <code>repeated double DoubleList = 5;</code>
     */
    public java.util.List<java.lang.Double>
        getDoubleListList() {
      return doubleList_;
    }
    /**
     * <code>repeated double DoubleList = 5;</code>
     */
    public int getDoubleListCount() {
      return doubleList_.size();
    }
    /**
     * <code>repeated double DoubleList = 5;</code>
     */
    public double getDoubleList(int index) {
      return doubleList_.get(index);
    }

    public static final int STRINGLIST_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList stringList_;
    /**
     * <code>repeated string StringList = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStringListList() {
      return stringList_;
    }
    /**
     * <code>repeated string StringList = 6;</code>
     */
    public int getStringListCount() {
      return stringList_.size();
    }
    /**
     * <code>repeated string StringList = 6;</code>
     */
    public java.lang.String getStringList(int index) {
      return stringList_.get(index);
    }
    /**
     * <code>repeated string StringList = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStringListBytes(int index) {
      return stringList_.getByteString(index);
    }

    public static final int DATETIMELIST_FIELD_NUMBER = 7;
    private java.util.List<java.lang.Long> dateTimeList_;
    /**
     * <code>repeated int64 DateTimeList = 7;</code>
     */
    public java.util.List<java.lang.Long>
        getDateTimeListList() {
      return dateTimeList_;
    }
    /**
     * <code>repeated int64 DateTimeList = 7;</code>
     */
    public int getDateTimeListCount() {
      return dateTimeList_.size();
    }
    /**
     * <code>repeated int64 DateTimeList = 7;</code>
     */
    public long getDateTimeList(int index) {
      return dateTimeList_.get(index);
    }

    public static final int BYTELIST_FIELD_NUMBER = 8;
    private java.util.List<com.google.protobuf.ByteString> byteList_;
    /**
     * <code>repeated bytes ByteList = 8;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getByteListList() {
      return byteList_;
    }
    /**
     * <code>repeated bytes ByteList = 8;</code>
     */
    public int getByteListCount() {
      return byteList_.size();
    }
    /**
     * <code>repeated bytes ByteList = 8;</code>
     */
    public com.google.protobuf.ByteString getByteList(int index) {
      return byteList_.get(index);
    }

    public static final int SEVERUNIXTIME_FIELD_NUMBER = 9;
    private java.util.List<java.lang.Long> severUnixTime_;
    /**
     * <code>repeated int64 SeverUnixTime = 9;</code>
     */
    public java.util.List<java.lang.Long>
        getSeverUnixTimeList() {
      return severUnixTime_;
    }
    /**
     * <code>repeated int64 SeverUnixTime = 9;</code>
     */
    public int getSeverUnixTimeCount() {
      return severUnixTime_.size();
    }
    /**
     * <code>repeated int64 SeverUnixTime = 9;</code>
     */
    public long getSeverUnixTime(int index) {
      return severUnixTime_.get(index);
    }

    private void initFields() {
      type_ = 0;
      ticket_ = 0;
      boolList_ = java.util.Collections.emptyList();
      intList_ = java.util.Collections.emptyList();
      doubleList_ = java.util.Collections.emptyList();
      stringList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      dateTimeList_ = java.util.Collections.emptyList();
      byteList_ = java.util.Collections.emptyList();
      severUnixTime_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTicket()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ticket_);
      }
      for (int i = 0; i < boolList_.size(); i++) {
        output.writeBool(3, boolList_.get(i));
      }
      for (int i = 0; i < intList_.size(); i++) {
        output.writeInt32(4, intList_.get(i));
      }
      for (int i = 0; i < doubleList_.size(); i++) {
        output.writeDouble(5, doubleList_.get(i));
      }
      for (int i = 0; i < stringList_.size(); i++) {
        output.writeBytes(6, stringList_.getByteString(i));
      }
      for (int i = 0; i < dateTimeList_.size(); i++) {
        output.writeInt64(7, dateTimeList_.get(i));
      }
      for (int i = 0; i < byteList_.size(); i++) {
        output.writeBytes(8, byteList_.get(i));
      }
      for (int i = 0; i < severUnixTime_.size(); i++) {
        output.writeInt64(9, severUnixTime_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ticket_);
      }
      {
        int dataSize = 0;
        dataSize = 1 * getBoolListList().size();
        size += dataSize;
        size += 1 * getBoolListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < intList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(intList_.get(i));
        }
        size += dataSize;
        size += 1 * getIntListList().size();
      }
      {
        int dataSize = 0;
        dataSize = 8 * getDoubleListList().size();
        size += dataSize;
        size += 1 * getDoubleListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stringList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(stringList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStringListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < dateTimeList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(dateTimeList_.get(i));
        }
        size += dataSize;
        size += 1 * getDateTimeListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < byteList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(byteList_.get(i));
        }
        size += dataSize;
        size += 1 * getByteListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < severUnixTime_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(severUnixTime_.get(i));
        }
        size += dataSize;
        size += 1 * getSeverUnixTimeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.xiwan.NettyGamer.proto.ServerResponse.payload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiwan.NettyGamer.proto.ServerResponse.payload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiwan.NettyGamer.proto.ServerResponse.payload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xiwan.NettyGamer.proto.ServerResponse.payload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xiwan.NettyGamer.proto.ServerResponse.payload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xiwan.NettyGamer.proto.ServerResponse.payload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.xiwan.NettyGamer.proto.ServerResponse.payload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.xiwan.NettyGamer.proto.ServerResponse.payload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.xiwan.NettyGamer.proto.ServerResponse.payload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.xiwan.NettyGamer.proto.ServerResponse.payload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xiwan.NettyGamer.proto.ServerResponse.payload prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.payload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.payload)
        com.xiwan.NettyGamer.proto.ServerResponse.payloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xiwan.NettyGamer.proto.ServerResponse.internal_static_protobuf_payload_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xiwan.NettyGamer.proto.ServerResponse.internal_static_protobuf_payload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xiwan.NettyGamer.proto.ServerResponse.payload.class, com.xiwan.NettyGamer.proto.ServerResponse.payload.Builder.class);
      }

      // Construct using com.xiwan.NettyGamer.proto.ServerResponse.payload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ticket_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        boolList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        intList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        doubleList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        stringList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        dateTimeList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        byteList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        severUnixTime_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xiwan.NettyGamer.proto.ServerResponse.internal_static_protobuf_payload_descriptor;
      }

      public com.xiwan.NettyGamer.proto.ServerResponse.payload getDefaultInstanceForType() {
        return com.xiwan.NettyGamer.proto.ServerResponse.payload.getDefaultInstance();
      }

      public com.xiwan.NettyGamer.proto.ServerResponse.payload build() {
        com.xiwan.NettyGamer.proto.ServerResponse.payload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xiwan.NettyGamer.proto.ServerResponse.payload buildPartial() {
        com.xiwan.NettyGamer.proto.ServerResponse.payload result = new com.xiwan.NettyGamer.proto.ServerResponse.payload(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ticket_ = ticket_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          boolList_ = java.util.Collections.unmodifiableList(boolList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.boolList_ = boolList_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          intList_ = java.util.Collections.unmodifiableList(intList_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.intList_ = intList_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          doubleList_ = java.util.Collections.unmodifiableList(doubleList_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.doubleList_ = doubleList_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          stringList_ = stringList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.stringList_ = stringList_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          dateTimeList_ = java.util.Collections.unmodifiableList(dateTimeList_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.dateTimeList_ = dateTimeList_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          byteList_ = java.util.Collections.unmodifiableList(byteList_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.byteList_ = byteList_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          severUnixTime_ = java.util.Collections.unmodifiableList(severUnixTime_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.severUnixTime_ = severUnixTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xiwan.NettyGamer.proto.ServerResponse.payload) {
          return mergeFrom((com.xiwan.NettyGamer.proto.ServerResponse.payload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xiwan.NettyGamer.proto.ServerResponse.payload other) {
        if (other == com.xiwan.NettyGamer.proto.ServerResponse.payload.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasTicket()) {
          setTicket(other.getTicket());
        }
        if (!other.boolList_.isEmpty()) {
          if (boolList_.isEmpty()) {
            boolList_ = other.boolList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureBoolListIsMutable();
            boolList_.addAll(other.boolList_);
          }
          onChanged();
        }
        if (!other.intList_.isEmpty()) {
          if (intList_.isEmpty()) {
            intList_ = other.intList_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureIntListIsMutable();
            intList_.addAll(other.intList_);
          }
          onChanged();
        }
        if (!other.doubleList_.isEmpty()) {
          if (doubleList_.isEmpty()) {
            doubleList_ = other.doubleList_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureDoubleListIsMutable();
            doubleList_.addAll(other.doubleList_);
          }
          onChanged();
        }
        if (!other.stringList_.isEmpty()) {
          if (stringList_.isEmpty()) {
            stringList_ = other.stringList_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureStringListIsMutable();
            stringList_.addAll(other.stringList_);
          }
          onChanged();
        }
        if (!other.dateTimeList_.isEmpty()) {
          if (dateTimeList_.isEmpty()) {
            dateTimeList_ = other.dateTimeList_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureDateTimeListIsMutable();
            dateTimeList_.addAll(other.dateTimeList_);
          }
          onChanged();
        }
        if (!other.byteList_.isEmpty()) {
          if (byteList_.isEmpty()) {
            byteList_ = other.byteList_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureByteListIsMutable();
            byteList_.addAll(other.byteList_);
          }
          onChanged();
        }
        if (!other.severUnixTime_.isEmpty()) {
          if (severUnixTime_.isEmpty()) {
            severUnixTime_ = other.severUnixTime_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureSeverUnixTimeIsMutable();
            severUnixTime_.addAll(other.severUnixTime_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasTicket()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xiwan.NettyGamer.proto.ServerResponse.payload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xiwan.NettyGamer.proto.ServerResponse.payload) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ ;
      /**
       * <code>required int32 Type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 Type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 Type = 1;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private int ticket_ ;
      /**
       * <code>required int32 Ticket = 2;</code>
       */
      public boolean hasTicket() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 Ticket = 2;</code>
       */
      public int getTicket() {
        return ticket_;
      }
      /**
       * <code>required int32 Ticket = 2;</code>
       */
      public Builder setTicket(int value) {
        bitField0_ |= 0x00000002;
        ticket_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 Ticket = 2;</code>
       */
      public Builder clearTicket() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ticket_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Boolean> boolList_ = java.util.Collections.emptyList();
      private void ensureBoolListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          boolList_ = new java.util.ArrayList<java.lang.Boolean>(boolList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated bool BoolList = 3;</code>
       */
      public java.util.List<java.lang.Boolean>
          getBoolListList() {
        return java.util.Collections.unmodifiableList(boolList_);
      }
      /**
       * <code>repeated bool BoolList = 3;</code>
       */
      public int getBoolListCount() {
        return boolList_.size();
      }
      /**
       * <code>repeated bool BoolList = 3;</code>
       */
      public boolean getBoolList(int index) {
        return boolList_.get(index);
      }
      /**
       * <code>repeated bool BoolList = 3;</code>
       */
      public Builder setBoolList(
          int index, boolean value) {
        ensureBoolListIsMutable();
        boolList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool BoolList = 3;</code>
       */
      public Builder addBoolList(boolean value) {
        ensureBoolListIsMutable();
        boolList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool BoolList = 3;</code>
       */
      public Builder addAllBoolList(
          java.lang.Iterable<? extends java.lang.Boolean> values) {
        ensureBoolListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, boolList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bool BoolList = 3;</code>
       */
      public Builder clearBoolList() {
        boolList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> intList_ = java.util.Collections.emptyList();
      private void ensureIntListIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          intList_ = new java.util.ArrayList<java.lang.Integer>(intList_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 IntList = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getIntListList() {
        return java.util.Collections.unmodifiableList(intList_);
      }
      /**
       * <code>repeated int32 IntList = 4;</code>
       */
      public int getIntListCount() {
        return intList_.size();
      }
      /**
       * <code>repeated int32 IntList = 4;</code>
       */
      public int getIntList(int index) {
        return intList_.get(index);
      }
      /**
       * <code>repeated int32 IntList = 4;</code>
       */
      public Builder setIntList(
          int index, int value) {
        ensureIntListIsMutable();
        intList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 IntList = 4;</code>
       */
      public Builder addIntList(int value) {
        ensureIntListIsMutable();
        intList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 IntList = 4;</code>
       */
      public Builder addAllIntList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIntListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, intList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 IntList = 4;</code>
       */
      public Builder clearIntList() {
        intList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Double> doubleList_ = java.util.Collections.emptyList();
      private void ensureDoubleListIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          doubleList_ = new java.util.ArrayList<java.lang.Double>(doubleList_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated double DoubleList = 5;</code>
       */
      public java.util.List<java.lang.Double>
          getDoubleListList() {
        return java.util.Collections.unmodifiableList(doubleList_);
      }
      /**
       * <code>repeated double DoubleList = 5;</code>
       */
      public int getDoubleListCount() {
        return doubleList_.size();
      }
      /**
       * <code>repeated double DoubleList = 5;</code>
       */
      public double getDoubleList(int index) {
        return doubleList_.get(index);
      }
      /**
       * <code>repeated double DoubleList = 5;</code>
       */
      public Builder setDoubleList(
          int index, double value) {
        ensureDoubleListIsMutable();
        doubleList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double DoubleList = 5;</code>
       */
      public Builder addDoubleList(double value) {
        ensureDoubleListIsMutable();
        doubleList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double DoubleList = 5;</code>
       */
      public Builder addAllDoubleList(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureDoubleListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, doubleList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double DoubleList = 5;</code>
       */
      public Builder clearDoubleList() {
        doubleList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList stringList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStringListIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          stringList_ = new com.google.protobuf.LazyStringArrayList(stringList_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string StringList = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStringListList() {
        return stringList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string StringList = 6;</code>
       */
      public int getStringListCount() {
        return stringList_.size();
      }
      /**
       * <code>repeated string StringList = 6;</code>
       */
      public java.lang.String getStringList(int index) {
        return stringList_.get(index);
      }
      /**
       * <code>repeated string StringList = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStringListBytes(int index) {
        return stringList_.getByteString(index);
      }
      /**
       * <code>repeated string StringList = 6;</code>
       */
      public Builder setStringList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListIsMutable();
        stringList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string StringList = 6;</code>
       */
      public Builder addStringList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListIsMutable();
        stringList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string StringList = 6;</code>
       */
      public Builder addAllStringList(
          java.lang.Iterable<java.lang.String> values) {
        ensureStringListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stringList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string StringList = 6;</code>
       */
      public Builder clearStringList() {
        stringList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string StringList = 6;</code>
       */
      public Builder addStringListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStringListIsMutable();
        stringList_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> dateTimeList_ = java.util.Collections.emptyList();
      private void ensureDateTimeListIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          dateTimeList_ = new java.util.ArrayList<java.lang.Long>(dateTimeList_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated int64 DateTimeList = 7;</code>
       */
      public java.util.List<java.lang.Long>
          getDateTimeListList() {
        return java.util.Collections.unmodifiableList(dateTimeList_);
      }
      /**
       * <code>repeated int64 DateTimeList = 7;</code>
       */
      public int getDateTimeListCount() {
        return dateTimeList_.size();
      }
      /**
       * <code>repeated int64 DateTimeList = 7;</code>
       */
      public long getDateTimeList(int index) {
        return dateTimeList_.get(index);
      }
      /**
       * <code>repeated int64 DateTimeList = 7;</code>
       */
      public Builder setDateTimeList(
          int index, long value) {
        ensureDateTimeListIsMutable();
        dateTimeList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 DateTimeList = 7;</code>
       */
      public Builder addDateTimeList(long value) {
        ensureDateTimeListIsMutable();
        dateTimeList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 DateTimeList = 7;</code>
       */
      public Builder addAllDateTimeList(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureDateTimeListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dateTimeList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 DateTimeList = 7;</code>
       */
      public Builder clearDateTimeList() {
        dateTimeList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.ByteString> byteList_ = java.util.Collections.emptyList();
      private void ensureByteListIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          byteList_ = new java.util.ArrayList<com.google.protobuf.ByteString>(byteList_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated bytes ByteList = 8;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getByteListList() {
        return java.util.Collections.unmodifiableList(byteList_);
      }
      /**
       * <code>repeated bytes ByteList = 8;</code>
       */
      public int getByteListCount() {
        return byteList_.size();
      }
      /**
       * <code>repeated bytes ByteList = 8;</code>
       */
      public com.google.protobuf.ByteString getByteList(int index) {
        return byteList_.get(index);
      }
      /**
       * <code>repeated bytes ByteList = 8;</code>
       */
      public Builder setByteList(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureByteListIsMutable();
        byteList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ByteList = 8;</code>
       */
      public Builder addByteList(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureByteListIsMutable();
        byteList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ByteList = 8;</code>
       */
      public Builder addAllByteList(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureByteListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, byteList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes ByteList = 8;</code>
       */
      public Builder clearByteList() {
        byteList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> severUnixTime_ = java.util.Collections.emptyList();
      private void ensureSeverUnixTimeIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          severUnixTime_ = new java.util.ArrayList<java.lang.Long>(severUnixTime_);
          bitField0_ |= 0x00000100;
         }
      }
      /**
       * <code>repeated int64 SeverUnixTime = 9;</code>
       */
      public java.util.List<java.lang.Long>
          getSeverUnixTimeList() {
        return java.util.Collections.unmodifiableList(severUnixTime_);
      }
      /**
       * <code>repeated int64 SeverUnixTime = 9;</code>
       */
      public int getSeverUnixTimeCount() {
        return severUnixTime_.size();
      }
      /**
       * <code>repeated int64 SeverUnixTime = 9;</code>
       */
      public long getSeverUnixTime(int index) {
        return severUnixTime_.get(index);
      }
      /**
       * <code>repeated int64 SeverUnixTime = 9;</code>
       */
      public Builder setSeverUnixTime(
          int index, long value) {
        ensureSeverUnixTimeIsMutable();
        severUnixTime_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 SeverUnixTime = 9;</code>
       */
      public Builder addSeverUnixTime(long value) {
        ensureSeverUnixTimeIsMutable();
        severUnixTime_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 SeverUnixTime = 9;</code>
       */
      public Builder addAllSeverUnixTime(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureSeverUnixTimeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, severUnixTime_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 SeverUnixTime = 9;</code>
       */
      public Builder clearSeverUnixTime() {
        severUnixTime_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.payload)
    }

    static {
      defaultInstance = new payload(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.payload)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_payload_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_payload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ServerResponse.proto\022\010protobuf\"\261\001\n\007pay" +
      "load\022\014\n\004Type\030\001 \002(\005\022\016\n\006Ticket\030\002 \002(\005\022\020\n\010Bo" +
      "olList\030\003 \003(\010\022\017\n\007IntList\030\004 \003(\005\022\022\n\nDoubleL" +
      "ist\030\005 \003(\001\022\022\n\nStringList\030\006 \003(\t\022\024\n\014DateTim" +
      "eList\030\007 \003(\003\022\020\n\010ByteList\030\010 \003(\014\022\025\n\rSeverUn" +
      "ixTime\030\t \003(\003B,\n\032com.xiwan.NettyGamer.pro" +
      "toB\016ServerResponse"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_payload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_payload_descriptor,
        new java.lang.String[] { "Type", "Ticket", "BoolList", "IntList", "DoubleList", "StringList", "DateTimeList", "ByteList", "SeverUnixTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
